---
extends: airbnb                            # We start with airbnb linting rules
parserOptions:
  ecmaVersion: 2017
env:
  node: true
  mocha: true
rules:
  no-use-before-define: 'off'              # recursive functions make this impossible
  strict: 'off'
  comma-dangle: 'off'
  no-template-curly-in-string: 'off'
  import/no-extraneous-dependencies: 'off'  # Gruntfile devDependencies
  no-param-reassign: 'off'
  prefer-spread: 'off'
  prefer-rest-params: 'off'
  max-len: ['error', 140, 2, {              # Set max line length to 140 chars
      ignoreUrls: true,
      ignoreComments: false,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
    }]
